### ISSUE TITLE
Verify violation line numbers in test suite

### ISSUE THREAD

**Issue by peterjc** [peterjc/flake8-rst-docstrings#49]
Currently ``tests/run_tests.sh`` has this code:

```bash
for code in RST??? ; do
    echo "======"
    echo $code
    echo "======"
    for file in $code/*.py ; do
        echo "flake8 --select RST $file"
        flake8 --select RST $file 2>&1 | grep ": $code "
    done
    echo "Good, $code violations reported, as expected."
done
```

Those examples contain in their module docstring the expected output, including line numbers, but we do not currently validate that. We'd have to move from bash to Python, but that would be worth doing at some point.

**Comment by xmo-odoo** [comment]
> We'd have to move from bash to Python, but that would be worth doing at some point.

Does that mean moving the test harness from (ba)sh to something like tox+pytest would be welcome?

Because in all honesty I kinda started doing that (the tox bit anyway, so it'd be easier to test against the advertised versions) for #48.

Incidentally, `setup.py` advertises 3.3+ (I thought it was 3.4+, not sure where I found that...), is that still desired / desirable?

**Comment by peterjc** [comment]
Cross reference #14 on trying pytest for the test suite. I'm not familiar with pytest though.

Currently the README says "Python 3.6 or later is recommended, but Python 3.3 onwards is also supported." but 789df27f5ba04bd1286397b1cf073c6c39f2e6d7 dropped Python 3.3 testing. I'll update the README and the setup file now... but without TravisCI testing the older versions (and them being very old now), it would be sensible to only support Python 3.6 onwards.

**Comment by xmo-odoo** [comment]
> Cross reference #14 on trying pytest for the test suite. I'm not familiar with pytest though.
> 
> Currently the README says "Python 3.6 or later is recommended, but Python 3.3 onwards is also supported." but [789df27](https://github.com/peterjc/flake8-rst-docstrings/commit/789df27f5ba04bd1286397b1cf073c6c39f2e6d7) dropped Python 3.3 testing. I'll update the README and the setup file now... but without TravisCI testing the older versions (and them being very old now), it would be sensible to only support Python 3.6 onwards.

That's good news. Porting the existing test suite to pytest seems to work pretty well from 3.4 onwards (though it requires some nudging as virtualenv dropped 3.4 this summer) but 3.3 is absolutely dead: its virtualenv doesn't even have a native pip so I've no idea how I could make it work.

Trying to add checks for the expected outputs is more challenging though, aside from the obvious and expected (that the expected outputs diverge from the actual because they were never checked) it looks like there are behavioural divergences between versions.

**Comment by peterjc** [comment]
Do you have an example of behavioural divergences between versions of Python?

I am aware of an AST change in Python 3.8 onwards caused a different line number to be reported (see #36), which we fixed.

**Comment by xmo-odoo** [comment]
> Do you have an example of behavioural divergences between versions of Python?

I first tried fixing the tests as of the latest Python (3.10), and it looks like the issue is with the <=3.7 branch of #36.

For instance for RST216 I get the correct line (9) from 3.8 to 3.10, but it's one off (10) below.

Also apparently under 3.4 the diff reported by pytest is the reverse order from every other which was quite confusing (technically neither is wrong per-se, just a matter of what's the "expected" in `assert a == b`).

**Comment by peterjc** [comment]
I would be happy to roll out a point release with a minimum of Python 3.6 - security releases for which stops this month: https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule

Even dropping Python 3.6, that still leaves Python 3.7 - so maybe reopen #36?

**Comment by xmo-odoo** [comment]
> I would be happy to roll out a point release with a minimum of Python 3.6 - security releases for which stops this month: [python.org/dev/peps/pep-0494/#and-beyond-schedule](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule)
> 
> Even dropping Python 3.6, that still leaves Python 3.7 - so maybe reopen #36?

The plot thickens interestingly! It looks like the issue is with #38 rather than #36, and that the problem might be the use of `splitlines` to know how many lines there are in the docstring: `str.splitlines` is peculiar because (today I learn) it ignores the trailing empty line, meaning
```python
"""x"""
```
is one line but
```python
"""x
"""
```
*is also one line*.

This means for module docstrings which start at the very top of the module (which depends on whether the project uses things like shebangs or coding tags or license reminders), if they have a newline they'll be "miss-offset".

The correct fix might be to just use `str.count('\n')`: it is simple and returns the right count, for files which use either unix or windows EOL conventions, which should be all of them: under python's own lexical analysis that only leaves "legacy" mac files (using `\r`).

Splitlines has much more complicated and extensive line-splitting boundaries, which don't match Python's own lexical analysis, and knowing whether there's an unseen extra line probably requires checking the last split line. It also has odd behaviours such as `''.splitlines() == []` (which in fairness matches `''.split()`, though not `''.split('\n')`.

**Comment by peterjc** [comment]
Well well well. I think that deserves a new issue all of its own - I was intending this (#49) for the general idea of testing we get the expected line numbers.

Counting ``\n`` sounds fine, we should be in text mode and not have ``\r`` to worry about.

**Comment by peterjc** [comment]
Thank you - I think this is a very worthwhile improvement in the testing :)
