### ISSUE TITLE
Is it possible to support Sphinx more holistically, as some kind of extension/addon?

### ISSUE THREAD

**Issue by gwerbin** [peterjc/flake8-rst-docstrings#74]
Sphinx has a really large number of directives and roles.

I made a best-effort attempt at whitelisting them all in a `.flake8` config file, assuming the `py` domain is set to the default, and the `js`, `c`, etc. domains are not used: https://gist.github.com/gwerbin/7a981694ae545f228e697058cff00ef3

This is a huge list, and it's not even exhaustive! It will need to be adjusted for different choices of `default-domain`, and it doesn't currently support any of the non-`py` domains. It might also go out of date between Sphinx versions.

It would be great if there was an `flake8-rst-docstrings[sphinx]` "extra" that could be installed to support all this. Hopefully Sphinx exposes this information in a public API that can be used for checks, instead of trying to maintain hard-coded lists like the above.

Is that something the maintainers would be interested in? Maybe someone with Sphinx development experience can comment on feasibility here.

**Comment by peterjc** [comment]
Are you really using all those roles in a single project? Surely not, but if so, why not just ignore ``RST304`` instead?

Anyway, see discussion on #7 (including the suggestion to use sphinx in nitpicking mode). Having ``flake8-rst-docstrings`` get a roles list from Sphinx at run time does not seem practical (although I'd be happy to be shown otherwise by a Sphinx expert).
